"""Textos da landing de parceiros, um dicionário por idioma.

Todas as chaves de "pt" precisam existir nos outros idiomas (build.py confere).
"""

LANGS = {
    "pt": {
        "html_lang": "pt-BR",
        "hreflang": "pt-BR",
        "og_locale": "pt_BR",
        "path": "",
        "code": "PT",
        "name": "Português",
        "flag": "br",
        "title": "Parceria para agências de viagem | Itacaré Ecolodge",
        "description": "Parceria B2B para agências de viagem: chalés privados na Mata Atlântica, a 10 minutos do centro de Itacaré (BA), com comissão atrativa e apresentação pronta em 4 idiomas.",
        "share_description": "Parceria para agências de viagem: chalés na Mata Atlântica em Itacaré (BA), comissão atrativa e apresentação pronta em 4 idiomas.",
        "share_image_alt": "Deck privativo de um chalé do Itacaré Ecolodge em meio à Mata Atlântica",
        "lang_nav_label": "Idioma",
        "logo_link_label": "Itacaré Ecolodge - site oficial",
        "logo_alt": "Logotipo do Itacaré Ecolodge",
        "eyebrow": "Para agências de viagem",
        "headline": "Leve seus clientes para o Itacaré Ecolodge",
        "hero_lead": "Chalés privados imersos na Mata Atlântica, a 10 minutos do centro de Itacaré (BA). Um produto pronto para vender, com comissão atrativa para sua agência.",
        "whatsapp_message": "Olá! Tenho interesse em conhecer a parceria B2B do Itacaré Ecolodge.",
        "btn_whatsapp": "Falar no WhatsApp",
        "btn_instagram": "Ver no Instagram",
        "values_title": "Por que fechar parceria com a gente",
        "values_lead": "Um produto de nicho, com apelo visual forte e fácil de incluir em roteiros pela Costa do Cacau.",
        "value1_title": "Comissão atrativa",
        "value1_text": "Condições comerciais diretas com o proprietário, sem intermediários.",
        "value2_title": "Material pronto para vender",
        "value2_text": "Apresentação completa, fotos profissionais e argumentos de venda prontos.",
        "value3_title": "Localização estratégica",
        "value3_text": "A 10 minutos do centro de Itacaré, fácil de incluir em qualquer roteiro da região.",
        "value4_title": "Suporte direto",
        "value4_text": "Fale direto com quem administra a pousada, sem burocracia.",
        "product_title": "Um produto que se vende sozinho",
        "product_text": "Chalés amplos, janelas panorâmicas para a mata, deck privativo suspenso e acabamento refinado. A estética natural do Itacaré Ecolodge já faz boa parte do trabalho de convencer o cliente.",
        "amenity1": "Ar-condicionado split em todos os chalés",
        "amenity2": "Deck privativo suspenso em meio à mata",
        "amenity3": "Wi-Fi de alta velocidade e Smart TV",
        "product_image_alt": "Quarto de um chalé do Itacaré Ecolodge com cama de casal, ar-condicionado e janela para a mata",
        "gallery_title": "Um pouco da experiência",
        "gallery1_caption": "Deck integrado à natureza",
        "gallery1_alt": "Deck de madeira com mesa e cadeiras suspenso entre as árvores da Mata Atlântica",
        "gallery2_caption": "Sala de estar aconchegante",
        "gallery2_alt": "Sala de estar do chalé com sofá, mesa de madeira e porta de vidro para a mata",
        "gallery3_caption": "Praias e surf a poucos minutos",
        "gallery3_alt": "Surfista fazendo uma manobra em uma onda no mar de Itacaré",
        "steps_title": "Como funciona a parceria",
        "step1_title": "Fale conosco",
        "step1_text": "Entre em contato pelo WhatsApp ou Instagram e conte um pouco sobre sua agência.",
        "step2_title": "Receba a apresentação",
        "step2_text": "Enviamos o material completo, com fotos, localização e condições comerciais.",
        "step3_title": "Feche a parceria",
        "step3_text": "Combinamos a comissão e você já pode começar a vender o Itacaré Ecolodge.",
        "downloads_title": "Baixe a apresentação completa",
        "downloads_lead": "Material com fotos, localização, estrutura e condições comerciais, disponível em 4 idiomas.",
        "contact_title": "Vamos conversar sobre a parceria?",
        "contact_lead": "Fale com a gente e receba a apresentação completa para levar aos seus clientes.",
        "website_label": "Site oficial",
        "footer_rights": "Todos os direitos reservados.",
        "footer_back": "Voltar para o site",
    },
    "en": {
        "html_lang": "en",
        "hreflang": "en",
        "og_locale": "en_US",
        "path": "en/",
        "code": "EN",
        "name": "English",
        "flag": "gb",
        "title": "Partnership for travel agencies | Itacaré Ecolodge",
        "description": "B2B partnership for travel agencies: private chalets in the Atlantic Forest, 10 minutes from downtown Itacaré (Bahia, Brazil), with an attractive commission and a ready-made presentation in 4 languages.",
        "share_description": "Partnership for travel agencies: chalets in the Atlantic Forest in Itacaré, Bahia, with an attractive commission and a presentation in 4 languages.",
        "share_image_alt": "Private deck of an Itacaré Ecolodge chalet surrounded by the Atlantic Forest",
        "lang_nav_label": "Language",
        "logo_link_label": "Itacaré Ecolodge - official website",
        "logo_alt": "Itacaré Ecolodge logo",
        "eyebrow": "For travel agencies",
        "headline": "Bring your clients to Itacaré Ecolodge",
        "hero_lead": "Private chalets immersed in the Atlantic Forest, 10 minutes from downtown Itacaré (Bahia, Brazil). A product ready to sell, with an attractive commission for your agency.",
        "whatsapp_message": "Hello! I'm interested in learning about the Itacaré Ecolodge B2B partnership.",
        "btn_whatsapp": "Chat on WhatsApp",
        "btn_instagram": "See us on Instagram",
        "values_title": "Why partner with us",
        "values_lead": "A niche product with strong visual appeal, easy to add to itineraries along Bahia's Cocoa Coast.",
        "value1_title": "Attractive commission",
        "value1_text": "Commercial terms agreed directly with the owner, with no middlemen.",
        "value2_title": "Sales-ready material",
        "value2_text": "A complete presentation, professional photos and ready-made selling points.",
        "value3_title": "Strategic location",
        "value3_text": "10 minutes from downtown Itacaré, easy to fit into any itinerary in the region.",
        "value4_title": "Direct support",
        "value4_text": "Talk directly to the people who run the lodge, with no red tape.",
        "product_title": "A product that sells itself",
        "product_text": "Spacious chalets, panoramic windows onto the forest, a private elevated deck and refined finishes. The natural beauty of Itacaré Ecolodge does much of the work of winning your client over.",
        "amenity1": "Split air conditioning in every chalet",
        "amenity2": "Private elevated deck in the middle of the forest",
        "amenity3": "High-speed Wi-Fi and Smart TV",
        "product_image_alt": "Bedroom in an Itacaré Ecolodge chalet with a double bed, air conditioning and a window onto the forest",
        "gallery_title": "A glimpse of the experience",
        "gallery1_caption": "A deck at one with nature",
        "gallery1_alt": "Wooden deck with a table and chairs raised among the trees of the Atlantic Forest",
        "gallery2_caption": "A cozy living room",
        "gallery2_alt": "Chalet living room with a sofa, a wooden table and a glass door opening onto the forest",
        "gallery3_caption": "Beaches and surf just minutes away",
        "gallery3_alt": "Surfer carving a wave off the coast of Itacaré",
        "steps_title": "How the partnership works",
        "step1_title": "Get in touch",
        "step1_text": "Reach out on WhatsApp or Instagram and tell us a little about your agency.",
        "step2_title": "Get the presentation",
        "step2_text": "We send you the complete material, with photos, location and commercial terms.",
        "step3_title": "Close the partnership",
        "step3_text": "We agree on the commission and you can start selling Itacaré Ecolodge right away.",
        "downloads_title": "Download the full presentation",
        "downloads_lead": "Material with photos, location, facilities and commercial terms, available in 4 languages.",
        "contact_title": "Shall we talk about a partnership?",
        "contact_lead": "Get in touch and receive the complete presentation to share with your clients.",
        "website_label": "Official website",
        "footer_rights": "All rights reserved.",
        "footer_back": "Visit our website",
    },
    "es": {
        "html_lang": "es",
        "hreflang": "es",
        "og_locale": "es_ES",
        "path": "es/",
        "code": "ES",
        "name": "Español",
        "flag": "es",
        "title": "Alianza para agencias de viaje | Itacaré Ecolodge",
        "description": "Alianza B2B para agencias de viaje: chalés privados en la Mata Atlántica, a 10 minutos del centro de Itacaré (Bahía, Brasil), con una comisión atractiva y una presentación lista en 4 idiomas.",
        "share_description": "Alianza para agencias de viaje: chalés en la Mata Atlántica en Itacaré, Bahía, con una comisión atractiva y una presentación en 4 idiomas.",
        "share_image_alt": "Deck privado de un chalé de Itacaré Ecolodge en medio de la Mata Atlántica",
        "lang_nav_label": "Idioma",
        "logo_link_label": "Itacaré Ecolodge - sitio web oficial",
        "logo_alt": "Logotipo de Itacaré Ecolodge",
        "eyebrow": "Para agencias de viaje",
        "headline": "Lleve a sus clientes a Itacaré Ecolodge",
        "hero_lead": "Chalés privados inmersos en la Mata Atlántica, a 10 minutos del centro de Itacaré (Bahía, Brasil). Un producto listo para vender, con una comisión atractiva para su agencia.",
        "whatsapp_message": "¡Hola! Me interesa conocer la alianza B2B de Itacaré Ecolodge.",
        "btn_whatsapp": "Hablar por WhatsApp",
        "btn_instagram": "Ver en Instagram",
        "values_title": "Por qué asociarse con nosotros",
        "values_lead": "Un producto de nicho, con un fuerte atractivo visual y fácil de incluir en itinerarios por la Costa del Cacao, en Bahía.",
        "value1_title": "Comisión atractiva",
        "value1_text": "Condiciones comerciales directas con el propietario, sin intermediarios.",
        "value2_title": "Material listo para vender",
        "value2_text": "Presentación completa, fotos profesionales y argumentos de venta listos.",
        "value3_title": "Ubicación estratégica",
        "value3_text": "A 10 minutos del centro de Itacaré, fácil de incluir en cualquier itinerario de la región.",
        "value4_title": "Atención directa",
        "value4_text": "Hable directamente con quienes administran el alojamiento, sin burocracia.",
        "product_title": "Un producto que se vende solo",
        "product_text": "Chalés amplios, ventanales panorámicos hacia el bosque, deck privado elevado y acabados refinados. La estética natural de Itacaré Ecolodge ya hace buena parte del trabajo de convencer al cliente.",
        "amenity1": "Aire acondicionado split en todos los chalés",
        "amenity2": "Deck privado elevado en medio del bosque",
        "amenity3": "Wi-Fi de alta velocidad y Smart TV",
        "product_image_alt": "Habitación de un chalé de Itacaré Ecolodge con cama doble, aire acondicionado y ventana hacia el bosque",
        "gallery_title": "Un poco de la experiencia",
        "gallery1_caption": "Deck integrado a la naturaleza",
        "gallery1_alt": "Deck de madera con mesa y sillas elevado entre los árboles de la Mata Atlántica",
        "gallery2_caption": "Sala de estar acogedora",
        "gallery2_alt": "Sala de estar del chalé con sofá, mesa de madera y puerta de vidrio hacia el bosque",
        "gallery3_caption": "Playas y surf a pocos minutos",
        "gallery3_alt": "Surfista haciendo una maniobra en una ola en el mar de Itacaré",
        "steps_title": "Cómo funciona la alianza",
        "step1_title": "Contáctenos",
        "step1_text": "Escríbanos por WhatsApp o Instagram y cuéntenos un poco sobre su agencia.",
        "step2_title": "Reciba la presentación",
        "step2_text": "Le enviamos el material completo, con fotos, ubicación y condiciones comerciales.",
        "step3_title": "Cierre la alianza",
        "step3_text": "Acordamos la comisión y usted ya puede empezar a vender Itacaré Ecolodge.",
        "downloads_title": "Descargue la presentación completa",
        "downloads_lead": "Material con fotos, ubicación, estructura y condiciones comerciales, disponible en 4 idiomas.",
        "contact_title": "¿Hablamos sobre la alianza?",
        "contact_lead": "Contáctenos y reciba la presentación completa para compartir con sus clientes.",
        "website_label": "Sitio web oficial",
        "footer_rights": "Todos los derechos reservados.",
        "footer_back": "Visitar nuestro sitio",
    },
    "de": {
        "html_lang": "de",
        "hreflang": "de",
        "og_locale": "de_DE",
        "path": "de/",
        "code": "DE",
        "name": "Deutsch",
        "flag": "de",
        "title": "Partnerschaft für Reisebüros | Itacaré Ecolodge",
        "description": "B2B-Partnerschaft für Reisebüros: private Bungalows im Atlantischen Regenwald, 10 Minuten vom Zentrum Itacarés (Bahia, Brasilien), mit attraktiver Provision und fertiger Präsentation in 4 Sprachen.",
        "share_description": "Partnerschaft für Reisebüros: Bungalows im Atlantischen Regenwald in Itacaré, Bahia, mit attraktiver Provision und Präsentation in 4 Sprachen.",
        "share_image_alt": "Private Terrasse eines Bungalows im Itacaré Ecolodge mitten im Atlantischen Regenwald",
        "lang_nav_label": "Sprache",
        "logo_link_label": "Itacaré Ecolodge - offizielle Website",
        "logo_alt": "Logo des Itacaré Ecolodge",
        "eyebrow": "Für Reisebüros",
        "headline": "Bringen Sie Ihre Kunden ins Itacaré Ecolodge",
        "hero_lead": "Private Bungalows mitten im Atlantischen Regenwald, 10 Minuten vom Zentrum Itacarés (Bahia, Brasilien). Ein verkaufsfertiges Produkt mit attraktiver Provision für Ihr Reisebüro.",
        "whatsapp_message": "Hallo! Ich interessiere mich für die B2B-Partnerschaft mit dem Itacaré Ecolodge.",
        "btn_whatsapp": "Per WhatsApp schreiben",
        "btn_instagram": "Auf Instagram ansehen",
        "values_title": "Warum eine Partnerschaft mit uns",
        "values_lead": "Ein Nischenprodukt mit starker visueller Wirkung, das sich leicht in Reiserouten entlang der Kakaoküste Bahias einbauen lässt.",
        "value1_title": "Attraktive Provision",
        "value1_text": "Direkte Geschäftskonditionen mit dem Eigentümer, ohne Zwischenhändler.",
        "value2_title": "Verkaufsfertiges Material",
        "value2_text": "Vollständige Präsentation, professionelle Fotos und fertige Verkaufsargumente.",
        "value3_title": "Strategische Lage",
        "value3_text": "10 Minuten vom Zentrum Itacarés, leicht in jede Reiseroute der Region einzubinden.",
        "value4_title": "Direkter Kontakt",
        "value4_text": "Sprechen Sie direkt mit den Betreibern der Unterkunft, ohne Bürokratie.",
        "product_title": "Ein Produkt, das sich von selbst verkauft",
        "product_text": "Geräumige Bungalows, Panoramafenster zum Wald, eine private erhöhte Terrasse und eine hochwertige Ausstattung. Die natürliche Ästhetik des Itacaré Ecolodge überzeugt Ihre Kunden fast von allein.",
        "amenity1": "Split-Klimaanlage in allen Bungalows",
        "amenity2": "Private erhöhte Terrasse mitten im Wald",
        "amenity3": "Schnelles WLAN und Smart-TV",
        "product_image_alt": "Schlafzimmer eines Bungalows im Itacaré Ecolodge mit Doppelbett, Klimaanlage und Fenster zum Wald",
        "gallery_title": "Ein Vorgeschmack auf das Erlebnis",
        "gallery1_caption": "Terrasse im Einklang mit der Natur",
        "gallery1_alt": "Holzterrasse mit Tisch und Stühlen zwischen den Bäumen des Atlantischen Regenwalds",
        "gallery2_caption": "Gemütliches Wohnzimmer",
        "gallery2_alt": "Wohnzimmer des Bungalows mit Sofa, Holztisch und Glastür zum Wald",
        "gallery3_caption": "Strände und Surfen in wenigen Minuten",
        "gallery3_alt": "Surfer bei einem Manöver auf einer Welle vor Itacaré",
        "steps_title": "So funktioniert die Partnerschaft",
        "step1_title": "Kontakt aufnehmen",
        "step1_text": "Schreiben Sie uns per WhatsApp oder Instagram und erzählen Sie uns kurz von Ihrem Reisebüro.",
        "step2_title": "Präsentation erhalten",
        "step2_text": "Wir senden Ihnen das vollständige Material mit Fotos, Lage und Geschäftskonditionen.",
        "step3_title": "Partnerschaft abschließen",
        "step3_text": "Wir vereinbaren die Provision und Sie können das Itacaré Ecolodge sofort verkaufen.",
        "downloads_title": "Die vollständige Präsentation herunterladen",
        "downloads_lead": "Material mit Fotos, Lage, Ausstattung und Geschäftskonditionen, verfügbar in 4 Sprachen.",
        "contact_title": "Sollen wir über eine Partnerschaft sprechen?",
        "contact_lead": "Kontaktieren Sie uns und erhalten Sie die vollständige Präsentation für Ihre Kunden.",
        "website_label": "Offizielle Website",
        "footer_rights": "Alle Rechte vorbehalten.",
        "footer_back": "Zu unserer Website",
    },
}
